site_name: Constitution of India
theme:
  name: material
  palette:
      primary: deep-orange
      accent: green

nav:
  - Preamble: index.md
  - Articles:
    - Part 1 - The Union and its Territory:
      - Article 1: articles/1.md


