site_name: Constitution of India
theme:
  name: material
  palette:
      primary: deep-orange
      accent: green

nav:
  - Preamble: index.md
  - Articles:
    - Part 1 - The Union and its Territory:
      - Article 1: articles/1.md
      - Article 2: articles/2.md
      - Article 3: articles/3.md
      - Article 4: articles/4.md
    - Part 2 - Citizenship:
      - Article 5: articles/5.md
      - Article 6: articles/6.md
      - Article 7: articles/7.md
      - Article 8: articles/8.md
      - Article 9: articles/9.md
      - Article 10: articles/10.md
      - Article 11: articles/11.md
    - Part 3 - Fundamental Rights:
      - General:
        - Article 12: articles/12.md
        - Article 13: articles/13.md
      - Right to Equality:
        - Article 14: articles/14.md
        - Article 15: articles/15.md
        - Article 16: articles/16.md
        - Article 17: articles/17.md
        - Article 18: articles/18.md